### ISSUE TITLE
Compatibility with older ARM versions

### ISSUE THREAD

**Issue by Br4v3H3r0** [gmh5225/AndroidDriveSignity#2]
Hi, 
Thanks for making this nice tool opensource for driver developers. It has helped me out a ton.

Just wanted to ask if this patching technique work for other versions of ARM? 
What changes are required in the script to make it compatible for older devices?

**Comment by gmh5225** [comment]
I don't have old devices. You need to test it yourself.
Please check ``check_version``,``check_modinfo`` and ``module_sig_check``.
